### ISSUE TITLE
tea加密建议用c++

### ISSUE THREAD

**Issue by shafle** [xjapanseikima/MotorolaTurboDispatcher#2]
tea加密建议用c++

**Comment by xjapanseikima** [comment]
好的,謝謝您的指教
能方便問下C++在TEA算法上的優點嗎？

**Comment by shafle** [comment]
> 好的,謝謝您的指教
> 能方便問下C++在TEA算法上的優點嗎？

C封装的四个密钥不容易被解密,另外Socket通讯均可以才用C封装,效率高不少,我试过你这个程序,JAVA的Socket速度太慢了,以至于屏幕更新迟钝,发出指令后返回速度接近150ms.

另外附 src/priv/chunyu/moto/DataProcesss/DataProcess.java中的 ReadingData方法可以这样

	public static StringBuilder ReadingData(byte[] bytes) {  
		sb.delete(0, sb.length());
		for (int index = 0, len = bytes.length; index <= len - 1; index += 1) {
			int char1 = ((bytes[index] >> 4) & 0xF);
			char chara1 = Character.forDigit(char1, 16);
			int char2 = ((bytes[index]) & 0xF);
			char chara2 = Character.forDigit(char2, 16);
			sb.append(chara1);
			sb.append(chara2);
		}
		return sb;
	}

改进后处理速度约快0.7ms/次返回处理

**Comment by xjapanseikima** [comment]
好的,
原來如此, 
對於Ｃ, 我較為不熟悉, 
等有空之餘會再改進
也對於速度慢感到頭疼, 原來是這個可以再優化
非常感謝您的指導！ 謝謝

**Comment by shafle** [comment]
> 好的,
> 原來如此,
> 對於Ｃ, 我較為不熟悉,
> 等有空之餘會再改進
> 也對於速度慢感到頭疼, 原來是這個可以再優化
> 非常感謝您的指導！ 謝謝

最近我也在研究这个XCMP协议,打算用在android上.计划全用C封装吧,效率会高一些.
