### ISSUE TITLE
Gps every minute

### ISSUE THREAD

**Issue by SunSayIsCool** [xjapanseikima/MotorolaTurboDispatcher#3]
Can you advise me how to make request for radios in the net to sending gps report every minute or every 25 meters?

**Comment by xjapanseikima** [comment]
Hi, you could take a look in MotorolaTurboDispatcher/MotorolaApp/src/priv/chunyu/moto/LocationRequestResponseProtocol/LRRPmsg.java
to see how the request made

**Comment by SunSayIsCool** [comment]
I saw it. But i can't understood how make the request string with different options
