### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by dnesteryuk** [xjapanseikima/MotorolaTurboDispatcher#4]
If the key isn't provided, you ask a [user to input it](https://github.com/xjapanseikima/MotorolaTurboDispatcher/blob/master/src/main/java/priv/chunyu/moto/TEA/TEA.java#L10). Where does this key come from?

**Comment by gunjubas** [comment]
This key comes from Motorola. It's proprietary.

**Comment by xjapanseikima** [comment]
thanks for the Maksym's answer,
yea, it's belong to Motorola authorisation, you can ask your region dealer for more detail
